name: L0-ContentProtection

on:
  push:
    paths:
      - ContentProtection/**
      - .github/workflows/*ContentProtection*.yml
  pull_request:
    paths:
      - ContentProtection/**
      - .github/workflows/*ContentProtection*.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{github.repository}}

      - name: Install valgrind, coverage, cmake
        run: |
          sudo apt update
          sudo apt install -y valgrind lcov cmake

      - name: Build Thunder
        working-directory: ${{github.workspace}}
        run: sh +x ${GITHUB_REPOSITORY}/.github/workflows/BuildThunder.sh

      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          cmake -S ${GITHUB_REPOSITORY}/ContentProtection/l0test -B build/contentprotectionl0test -DCMAKE_INSTALL_PREFIX="install" -DCMAKE_CXX_FLAGS="--coverage -Wall -Werror"
          cmake --build build/contentprotectionl0test --target install

      - name: Run
        working-directory: ${{github.workspace}}
        run: PATH=${PWD}/install/bin:${PATH} LD_LIBRARY_PATH=${PWD}/install/lib:${LD_LIBRARY_PATH} valgrind --tool=memcheck --log-file=valgrind_log --leak-check=yes --show-reachable=yes --track-fds=yes --fair-sched=try contentprotectionl0test

      - name: Generate coverage
        working-directory: ${{github.workspace}}
        run: |
          lcov -c -o coverage.info -d build/contentprotectionl0test
          genhtml -o coverage coverage.info

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            coverage/
            valgrind_log
          if-no-files-found: warn
