name: L0-PersistentStore-grpc

on:
  push:
    paths:
      - PersistentStore/grpc/**
  pull_request:
    paths:
      - PersistentStore/grpc/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: rdkservices

      - name: Install valgrind, cmake, protoc, grpc_cpp_plugin, grpc
        run: |
          sudo apt update
          sudo apt install -y valgrind cmake protobuf-compiler protobuf-compiler-grpc libgrpc++-dev

      - name: Build Thunder
        working-directory: ${{github.workspace}}
        run: sh +x rdkservices/.github/workflows/BuildThunder.sh

      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          cmake -S rdkservices/PersistentStore/grpc/l0test -B build/persistentstoregrpcl0test -DCMAKE_INSTALL_PREFIX="install/usr" -DCMAKE_CXX_FLAGS="-Wall -Werror"
          cmake --build build/persistentstoregrpcl0test --target install

      - name: Run
        working-directory: ${{github.workspace}}
        run: PATH=${PWD}/install/usr/bin:${PATH} LD_LIBRARY_PATH=${PWD}/install/usr/lib:${LD_LIBRARY_PATH} valgrind --tool=memcheck --log-file=valgrind_log --leak-check=yes --show-reachable=yes --track-fds=yes --fair-sched=try grpcl0test
